### ISSUE TITLE
Multi-loader jar doesn't merge correctly, causing NeoForge mixins to not refmap correctly.

### ISSUE THREAD

**Issue by Merith-TK** [MCLegoMan/oneslotatatime#2]
Neoforged Version: 21.1.119
Mod Version, 1.0.0 (1.0.1 release)
MC Version: 1.21.1

https://mclo.gs/0XVa66z

![Image](https://github.com/user-attachments/assets/a5c609c5-8a05-4dfc-8941-bbeea927a799)

![Image](https://github.com/user-attachments/assets/419fecbe-46fe-4fe3-8040-0cd77ba5f8c0)

**Comment by mclegoman** [comment]
Seems like a mappings issue, I'll recompile for the latest version.

**Comment by mclegoman** [comment]
This was a weird one, but I've found a fix.
The issue was related to how we merge the fabric, quilt, and neoforge jars together.
Using the platform specific jar works just fine.

I've uploaded the fabric, quilt, and neoforge platform specific versions to modrinth, and here on github.
https://modrinth.com/mod/oneslotatatime/version/1.0.2
https://github.com/mclegoman/oneslotatatime/releases/tag/1.0.2%2B1.21.1

**Comment by Merith-TK** [comment]
So problem, most mod managers, only let you download the "primary file" of a release. In this case that is the bundled-jar
Meaning I cant include the mod in my modpack *unless* I directly bundle the neoforged jar. 

Most mod's on the platform create seperate releases with the same data for each supported platform, 

PrismLauncher
![Image](https://github.com/user-attachments/assets/75b357f1-2450-4848-b1b6-34ad3826d07c)


Packiz `mod.pw.toml`
```toml
name = "One Slot at a Time"
filename = "mclm_osaat-1.0.2+1.21.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/L76YsJKa/versions/zH2ldYNO/mclm_osaat-1.0.2%2B1.21.1.jar"
hash-format = "sha512"
hash = "d245fb9418c339b5964a42304649b5d83b6e75ffb09d5c83ec3502fc37e357df8293c5d634ca76b448fdbae297794c30273a010c05891209e11176742e946647"

[update]
[update.modrinth]
mod-id = "L76YsJKa"
version = "zH2ldYNO"
```

The Modrinth launcher you have to go in and *specifically* select that alternative file otherwise it will download the "primary file"
